name: viz_dart_ecc
description: Elliptic curve cryptography lib for VIZ based blockchain in Dart lang.
version: 1.0.1
homepage: https://github.com/VizTower/viz_dart_ecc
authors:
  - ivanzar <ivanzar.developer@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  base58check: ^1.0.1
  pointycastle: ^1.0.1
  convert: ^2.1.1

dev_dependencies:
  test: ^1.0.0
